
server:
  port: 9999

spring:
  cloud:
    gateway:
      #discovery:
        #locator:
          #enabled: true
      routes:
      - id: limit_route
        uri: http://47.102.192.50:8801 # http://47.102.192.50:8081  #  lb://consumer-service lb 代表从注册中心获取服务，且已负载均衡方式转发
        predicates:
        - Path=/**/** #只漏油转发
        filters:
        - name: RequestRateLimiter #名称必须是RequestRateLimiter
          args:
            key-resolver: "#{@ipResolver}"  #使用SpEL按名称引用bean
            redis-rate-limiter.replenishRate: 2 #允许用户每秒处理多少个请求
            redis-rate-limiter.burstCapacity: 3 #令牌桶的容量，允许在一秒钟内完成的最大请求数
        - name: Hystrix #断路器的配置
          args:
            name: fallbackcmd
            fallbackUri: forward:/defaultfallback
  #application: #注册中心 服务名
    #name: spring-cloub-gateway
  redis:
    host: localhost
    port: 6379
    database: 0

#eureka: #将服务注册到注册中心
  #client:
    #service-url:
      #defaultZone: http://47.102.192.50:8080/eureka/

hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 6000





